######################################################################
# Automatically generated by qmake (2.01a) Sat May 23 17:38:44 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwidget.h videodevice.h
SOURCES += main.cpp mainwidget.cpp videodevice.cpp
