######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 8 18:43:09 2017
######################################################################

TEMPLATE = app
TARGET = 
INCLUDEPATH += . /opt/oencv-3.2.0/include/ \
				/opt/oencv-3.2.0/include/opencv \
				/opt/oencv-3.2.0/include/opencv2 



# Input
HEADERS += mainwidget.h tools.h 
SOURCES += main.cpp \
           mainwidget.cpp \
           tools.cpp 
