######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 7 12:55:20 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . capture_person/helloqt
INCLUDEPATH += .

# Input
HEADERS += mainwidget.h tools.h videodevice.h
SOURCES += main.cpp \
           mainwidget.cpp \
           tools.cpp \
           videodevice.cpp 
